//RELATORIO QUE INFORMA O CONSUMO MEDIO DO VEICULO: KM RODADOS/LITROS ABASTECIDOS
//PRA CADA ABASTECIMENTO DO TIPO COMPLETO (TANQUE CHEIO)
package relatorio;

public class RelatorioConsumoDoVeiculo {

}
